name: Daily GPS Sensor Report

on:
  schedule:
    # Run at 00:00 UTC daily (adjust time as needed)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git credentials
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
    
    - name: Run GPS Sensor Report Script
      env:
        # Store sensitive information as encrypted GitHub Secrets
        GPS_API_KEY: ${{ secrets.GPS_API_KEY }}
        GPS_DEVICE_ID: ${{ secrets.GPS_DEVICE_ID }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python scripts/gps_sensor_report.py
